-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 15:39:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema happiness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema happiness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happiness` DEFAULT CHARACTER SET utf8mb4 ;
USE `happiness` ;

-- -----------------------------------------------------
-- Table `happiness`.`years`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness`.`years` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happiness`.`all_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness`.`all_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happiness`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness`.`regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` TEXT(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happiness`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` TEXT(45) NULL,
  `regions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `regions_id`),
  INDEX `fk_countries_regions_idx` (`regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_countries_regions`
    FOREIGN KEY (`regions_id`)
    REFERENCES `happiness`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happiness`.`countries_has_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happiness`.`countries_has_date` (
  `countries_id` INT NOT NULL,
  `countries_regions_id` INT NOT NULL,
  `date_id` INT NOT NULL,
  `values_happiness_rank_id` INT NOT NULL,
  `values_happiness_score_id` INT NOT NULL,
  `values_health_score_id` INT NOT NULL,
  PRIMARY KEY (`countries_id`, `countries_regions_id`, `date_id`, `values_happiness_rank_id`, `values_happiness_score_id`, `values_health_score_id`),
  INDEX `fk_countries_has_date_date1_idx` (`date_id` ASC) VISIBLE,
  INDEX `fk_countries_has_date_countries1_idx` (`countries_id` ASC, `countries_regions_id` ASC) VISIBLE,
  INDEX `fk_countries_has_date_values1_idx` (`values_happiness_rank_id` ASC) VISIBLE,
  INDEX `fk_countries_has_date_values2_idx` (`values_happiness_score_id` ASC) VISIBLE,
  INDEX `fk_countries_has_date_values3_idx` (`values_health_score_id` ASC) VISIBLE,
  CONSTRAINT `fk_countries_has_date_countries1`
    FOREIGN KEY (`countries_id` , `countries_regions_id`)
    REFERENCES `happiness`.`countries` (`id` , `regions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_countries_has_date_date1`
    FOREIGN KEY (`date_id`)
    REFERENCES `happiness`.`years` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_countries_has_date_values1`
    FOREIGN KEY (`values_happiness_rank_id`)
    REFERENCES `happiness`.`all_values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_countries_has_date_values2`
    FOREIGN KEY (`values_happiness_score_id`)
    REFERENCES `happiness`.`all_values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_countries_has_date_values3`
    FOREIGN KEY (`values_health_score_id`)
    REFERENCES `happiness`.`all_values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
